"""change trades table to use composite key

Revision ID: b98925097a18
Revises: 555e362778f7
Create Date: 2021-07-29 09:44:08.604500

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b98925097a18'
down_revision = '555e362778f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('trades', 'stock_id',
    #                 existing_type=sa.INTEGER(),
    #                 nullable=False)
    # op.alter_column('trades', 'user_id',
    #                 existing_type=sa.INTEGER(),
    #                 nullable=False)
    #  op.drop_column('trades', 'id')
    # ### end Alembic commands ###

    # Custom migration code to fix upgrade issue
    with op.batch_alter_table('trades') as batch_op:
        batch_op.alter_column('stock_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.drop_column('id')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('id', sa.INTEGER(), nullable=False))
    op.alter_column('trades', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('trades', 'stock_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
